# Setup
title:               Lanyon
tagline:             'Lanyon'
description:         'My Blog'
url:                 
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author: Abas
  name: Abasty             
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
