# Setup
title:               Blog
tagline:             'Blogku'
description:         'Blogku'
url:                 
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author: 
  name: Abasty             
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
